I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 186, in script
    c "fiu, por un pelo"
Exception: Sayer 'c' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 186, in script
    c "fiu, por un pelo"
  File "C:\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'c' is not defined.

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
I`m Bayron Mental 1.0
Sun Oct 22 13:03:18 2023
